apiVersion: chaos-mesh.org/v1alpha1
kind: networkchaos
metadata:
  name: network-delay-example
  namespace: chaos-testing
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - appns
    labelSelectors:
      "app": "nginx"
  delay:
    latency: "10ms"
    correlation: "100"
    jitter: "0ms"
  duration: "30s"
   
